/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CharacterSetupRouteImport } from './routes/character-setup'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OwnerRouteRouteImport } from './routes/owner/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedCustomizeRouteImport } from './routes/_authenticated/customize'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQuestsRouteImport } from './routes/_authenticated/quests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as OwnerMapEditorRouteImport } from './routes/owner/map-editor'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedPaymentCancelRouteImport } from './routes/_authenticated/payment.cancel'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated/payment.success'
import { Route as ApiPublicBootstrapOwnerRouteImport } from './routes/api/public/bootstrap-owner'
import { Route as ApiPublicOwnerAlertsRouteImport } from './routes/api/public/owner-alerts'
import { Route as ApiPublicPaypalIpnRouteImport } from './routes/api/public/paypal/ipn'
import { Route as ApiPublicPaypalReturnRouteImport } from './routes/api/public/paypal/return'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterSetupRoute = CharacterSetupRouteImport.update({
  id: '/character-setup',
  path: '/character-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRouteRoute = OwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomizeRoute = AuthenticatedCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestsRoute = AuthenticatedQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerMapEditorRoute = OwnerMapEditorRouteImport.update({
  id: '/map-editor',
  path: '/map-editor',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPaymentCancelRoute =
  AuthenticatedPaymentCancelRouteImport.update({
    id: '/payment/cancel',
    path: '/payment/cancel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapOwnerRoute = ApiPublicBootstrapOwnerRouteImport.update({
  id: '/api/public/bootstrap-owner',
  path: '/api/public/bootstrap-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOwnerAlertsRoute = ApiPublicOwnerAlertsRouteImport.update({
  id: '/api/public/owner-alerts',
  path: '/api/public/owner-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalIpnRoute = ApiPublicPaypalIpnRouteImport.update({
  id: '/api/public/paypal/ipn',
  path: '/api/public/paypal/ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalReturnRoute = ApiPublicPaypalReturnRouteImport.update({
  id: '/api/public/paypal/return',
  path: '/api/public/paypal/return',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/character-setup': typeof CharacterSetupRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/customize': typeof AuthenticatedCustomizeRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/owner/map-editor': typeof OwnerMapEditorRoute
  '/owner/': typeof OwnerIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/api/public/bootstrap-owner': typeof ApiPublicBootstrapOwnerRoute
  '/api/public/owner-alerts': typeof ApiPublicOwnerAlertsRoute
  '/api/public/paypal/ipn': typeof ApiPublicPaypalIpnRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/character-setup': typeof CharacterSetupRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/customize': typeof AuthenticatedCustomizeRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/owner/map-editor': typeof OwnerMapEditorRoute
  '/owner': typeof OwnerIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/api/public/bootstrap-owner': typeof ApiPublicBootstrapOwnerRoute
  '/api/public/owner-alerts': typeof ApiPublicOwnerAlertsRoute
  '/api/public/paypal/ipn': typeof ApiPublicPaypalIpnRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/owner': typeof OwnerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/character-setup': typeof CharacterSetupRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/customize': typeof AuthenticatedCustomizeRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quests': typeof AuthenticatedQuestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/owner/map-editor': typeof OwnerMapEditorRoute
  '/owner/': typeof OwnerIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/api/public/bootstrap-owner': typeof ApiPublicBootstrapOwnerRoute
  '/api/public/owner-alerts': typeof ApiPublicOwnerAlertsRoute
  '/api/public/paypal/ipn': typeof ApiPublicPaypalIpnRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/auth'
    | '/character-setup'
    | '/mcp'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/oauth-protected-resource'
    | '/credits'
    | '/customize'
    | '/history'
    | '/inventory'
    | '/messages'
    | '/play'
    | '/profile'
    | '/quests'
    | '/settings'
    | '/vendor'
    | '/owner/map-editor'
    | '/owner/'
    | '/.lovable/oauth/consent'
    | '/payment/cancel'
    | '/payment/success'
    | '/api/public/bootstrap-owner'
    | '/api/public/owner-alerts'
    | '/api/public/paypal/ipn'
    | '/api/public/paypal/return'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/character-setup'
    | '/mcp'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/oauth-protected-resource'
    | '/credits'
    | '/customize'
    | '/history'
    | '/inventory'
    | '/messages'
    | '/play'
    | '/profile'
    | '/quests'
    | '/settings'
    | '/vendor'
    | '/owner/map-editor'
    | '/owner'
    | '/.lovable/oauth/consent'
    | '/payment/cancel'
    | '/payment/success'
    | '/api/public/bootstrap-owner'
    | '/api/public/owner-alerts'
    | '/api/public/paypal/ipn'
    | '/api/public/paypal/return'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/owner'
    | '/auth'
    | '/character-setup'
    | '/mcp'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/credits'
    | '/_authenticated/customize'
    | '/_authenticated/history'
    | '/_authenticated/inventory'
    | '/_authenticated/messages'
    | '/_authenticated/play'
    | '/_authenticated/profile'
    | '/_authenticated/quests'
    | '/_authenticated/settings'
    | '/_authenticated/vendor'
    | '/owner/map-editor'
    | '/owner/'
    | '/.lovable/oauth/consent'
    | '/_authenticated/payment/cancel'
    | '/_authenticated/payment/success'
    | '/api/public/bootstrap-owner'
    | '/api/public/owner-alerts'
    | '/api/public/paypal/ipn'
    | '/api/public/paypal/return'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  OwnerRouteRoute: typeof OwnerRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CharacterSetupRoute: typeof CharacterSetupRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicBootstrapOwnerRoute: typeof ApiPublicBootstrapOwnerRoute
  ApiPublicOwnerAlertsRoute: typeof ApiPublicOwnerAlertsRoute
  ApiPublicPaypalIpnRoute: typeof ApiPublicPaypalIpnRoute
  ApiPublicPaypalReturnRoute: typeof ApiPublicPaypalReturnRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-setup': {
      id: '/character-setup'
      path: '/character-setup'
      fullPath: '/character-setup'
      preLoaderRoute: typeof CharacterSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customize': {
      id: '/_authenticated/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof AuthenticatedCustomizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quests': {
      id: '/_authenticated/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthenticatedQuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/owner/map-editor': {
      id: '/owner/map-editor'
      path: '/map-editor'
      fullPath: '/owner/map-editor'
      preLoaderRoute: typeof OwnerMapEditorRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/payment/cancel': {
      id: '/_authenticated/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof AuthenticatedPaymentCancelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-owner': {
      id: '/api/public/bootstrap-owner'
      path: '/api/public/bootstrap-owner'
      fullPath: '/api/public/bootstrap-owner'
      preLoaderRoute: typeof ApiPublicBootstrapOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/owner-alerts': {
      id: '/api/public/owner-alerts'
      path: '/api/public/owner-alerts'
      fullPath: '/api/public/owner-alerts'
      preLoaderRoute: typeof ApiPublicOwnerAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/ipn': {
      id: '/api/public/paypal/ipn'
      path: '/api/public/paypal/ipn'
      fullPath: '/api/public/paypal/ipn'
      preLoaderRoute: typeof ApiPublicPaypalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/return': {
      id: '/api/public/paypal/return'
      path: '/api/public/paypal/return'
      fullPath: '/api/public/paypal/return'
      preLoaderRoute: typeof ApiPublicPaypalReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedCustomizeRoute: typeof AuthenticatedCustomizeRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestsRoute: typeof AuthenticatedQuestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
  AuthenticatedPaymentCancelRoute: typeof AuthenticatedPaymentCancelRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedCustomizeRoute: AuthenticatedCustomizeRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestsRoute: AuthenticatedQuestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
  AuthenticatedPaymentCancelRoute: AuthenticatedPaymentCancelRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OwnerRouteRouteChildren {
  OwnerMapEditorRoute: typeof OwnerMapEditorRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteRouteChildren: OwnerRouteRouteChildren = {
  OwnerMapEditorRoute: OwnerMapEditorRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteRouteWithChildren = OwnerRouteRoute._addFileChildren(
  OwnerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OwnerRouteRoute: OwnerRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CharacterSetupRoute: CharacterSetupRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicBootstrapOwnerRoute: ApiPublicBootstrapOwnerRoute,
  ApiPublicOwnerAlertsRoute: ApiPublicOwnerAlertsRoute,
  ApiPublicPaypalIpnRoute: ApiPublicPaypalIpnRoute,
  ApiPublicPaypalReturnRoute: ApiPublicPaypalReturnRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
